% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  aquas.m

% Este script es el que hace comenzar a toda la
% aplicacion.


clear all;
close all;

format long;


%Evitamos que salgan los warnings al hacer la integral numerica
%warning off MATLAB:quad:MinStepSize;
%warning off MATLAB:quad:ImproperFcnValue;

% Se crea una nueva ventana

figure('Units', 'normalized',...
		'Position', [0.05 0.05 0.9 0.9],...
        'MenuBar', 'none', ...
        'name', 'AQUAS: Application for solving QUeuing problems Analytically and using Simulation', ...
        'NumberTitle', 'off', ...
        'resize','off');

frame_inicio_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.702 .702 .702],...
   'Position', [0.2 0.18 0.6 0.75]);

frame_inicio_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.60 .60 .60],...
   'Position', [0.34 0.76 0.28 0.11]);


% La variable eleccion es un numero que esta asociado
% al modelo de colas o red de colas que ha elegido el 
% usuario, en funcion del orden que ocupan en el popup.

% Si no selecciona ningun valor, se asumira
% que quiere resolver un modelo M/M/1, y es por ello
% que toma el valor 1.

eleccion = 1;

%Inicializa algunas variables de control

cambiar_parametros_mm=0;


cambios_en_modelo=0;

intercambio_cerradas=0;

global estoy_en_redes_abiertas;

estoy_en_redes_abiertas=0;


text_inicio = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'AQUAS', ...
   'Units', 'normalized', ...
   'Position', [0.38 0.78 0.2 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.8, ...
   'FontWeight', 'Bold', ...
   'FontAngle', 'Oblique', ...
   'FontName', 'Verdana', ...
   'ForegroundColor', [0 0 0.8], ...
   'BackgroundColor', [.6 .6 .6],...
   'HorizontalAlignment', 'Center');


text_inicio_2 = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Seleccione la opcion que desea:', ...
   'Units', 'normalized', ...
   'Position', [0.35 0.5 0.3 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.4, ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

boton_cerrar = uicontrol(gcf, 'Style', 'Pushbutton',...
   'String', 'X', 'Value', 0, ...
   'Units', 'normalized', ...
   'Position', [0.74 0.86 0.05 0.05], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.7, ...
   'Callback', 'cerrar_ventana');

boton_info = uicontrol(gcf, 'Style', 'Pushbutton',...
   'String', 'Info', 'Value', 0, ...
   'Units', 'normalized', ...
   'Position', [0.74 0.75 0.05 0.05], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.4, ...
   'Callback', 'info');



boton_resolucion_simulacion = uicontrol(gcf, 'Style', 'Pushbutton',...
   'String', 'Resolucion por Simulacion', 'Value', 0, ...
   'Units', 'normalized', ...
   'Position', [0.25 0.25 0.22 0.1], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.22, ...
   'Callback', 'resolver_simulacion');

boton_resolucion_analitica = uicontrol(gcf, 'Style', 'Pushbutton',...
   'String', 'Resolucion Analitica', 'Value', 0, ...
   'Units', 'normalized', ...
   'Position', [0.55 0.25 0.22 0.1], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.2, ...
   'Callback', 'resolver_analitica');


