% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  calcular_p_clientes_cerradas.m

%Se encarga de calcular la probabilidad de que halla
%un determinado numero de clientes en un nodo de la red cerrada

texto_probabilidad_clientes='No Error';
error_p_clientes_cerradas=0;

numero_clientes_probabilidad_n = get(numero_clientes_probabilidad, 'String');
numero_clientes_probabilidad_n = str2num(numero_clientes_probabilidad_n);

numero_nodo_probabilidad_n = get(numero_nodo_probabilidad, 'String');
numero_nodo_probabilidad_n = str2num(numero_nodo_probabilidad_n);



%Verifica si los parametros son correctos
if (numero_clientes_probabilidad_n >=0 & floor(numero_clientes_probabilidad_n)==numero_clientes_probabilidad_n &...
      ceil(numero_clientes_probabilidad_n)==numero_clientes_probabilidad_n & numero_clientes_probabilidad_n<clientes_cerradas &...
      numero_nodo_probabilidad_n>0 & numero_nodo_probabilidad_n<=nodos_cerradas & ...
      numero_nodo_probabilidad_n==floor(numero_nodo_probabilidad_n) &...
      numero_nodo_probabilidad_n==ceil(numero_nodo_probabilidad_n))

   %La probabilidad es un elemento de la matriz matriz_p_clientes_cerradas
   texto_probabilidad_clientes=num2str(matriz_p_clientes_cerradas(numero_nodo_probabilidad_n,numero_clientes_probabilidad_n+1));
else
   texto_probabilidad_clientes = 'Error';
   error_p_clientes_cerradas=1;
end   


if (error_p_clientes_cerradas==1)
   text_redes_cerradas_salida_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
    'String', texto_probabilidad_clientes, ...
    'Units', 'normalized', ...
	'Position', [0.7 0.35  0.1 0.03], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.6, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'r', ...
	'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');
else
   text_redes_cerradas_salida_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
    'String', texto_probabilidad_clientes, ...
    'Units', 'normalized', ...
	'Position', [0.7 0.35  0.1 0.03], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.6, ...
	'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');
end

