% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  detalles_nodo.m


% Obtiene los detalles de un nodo de la red abierta a partir de los valores de 
% lamba, mu y s. Lo hace llamando a salida

nodo_n = get(nodo, 'String');
nodo_n = str2num(nodo_n);


if (nodo_n>0 & nodo_n<=nodos_abiertas & nodo_n==ceil(nodo_n) & nodo_n==floor(nodo_n))

   text_detalles_nodo_1 = uicontrol(gcf, 'Style', 'Text', ...
      'String', ' ', ...
   	  'Units', 'normalized', ...
	  'Position', [0.72 0.36 0.15 0.05], ...
      'BackgroundColor', [.6 .6 .6],...
      'FontUnits', 'normalized', ...
      'FontSize', 0.3, ...
      'HorizontalAlignment', 'Center'); 
   
	mu_n=vector_mu_abiertas(nodo_n);
	s_n=vector_servidores_abiertas(nodo_n);
    lambda_n=lambda_mayuscula(nodo_n);
   
    cambiar_parametros_mm=1;

	salida;

else
   
   text_detalles_nodo_1 = uicontrol(gcf, 'Style', 'Text', ...
      'String', 'ERROR EN LOS PARAMETROS ', ...
   	  'Units', 'normalized', ...
	  'Position', [0.72 0.36 0.15 0.05], ...
      'BackgroundColor', [.6 .6 .6],...
      'FontWeight', 'bold', ...
      'ForegroundColor', 'r',...
      'FontUnits', 'normalized', ...
      'FontSize', 0.35, ...
      'HorizontalAlignment', 'Center'); 
end
