% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  dibujar_p_cerradas.m

%Muestra en forma de diagrma de barras la probabilida de que exista
%un rango de clientes en un determinado nodo de la red cerrada


%texto_probabilidad_clientes='No Error';
%error_p_clientes_cerradas=0;

numero_clientes_intervalo1_n = get(numero_clientes_intervalo1, 'String');
numero_clientes_intervalo1_n = str2num(numero_clientes_intervalo1_n);

numero_clientes_intervalo2_n = get(numero_clientes_intervalo2, 'String');
numero_clientes_intervalo2_n = str2num(numero_clientes_intervalo2_n);

numero_nodo_intervalo_dibujar_n = get(numero_nodo_intervalo_dibujar, 'String');
numero_nodo_intervalo_dibujar_n = str2num(numero_nodo_intervalo_dibujar_n);


text_redes_cerradas_intervalo_error = uicontrol(gcf, 'Style', 'Text', ...
    'String', '', ...
    'Units', 'normalized', ...
	'Position', [0.15 0.58  0.2 0.03], ...
    'FontUnits', 'normalized', ...        
	'FontSize', 0.2, ...
    'ForegroundColor', 'r', ...
	'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');


global dibujo3;



if (numero_clientes_intervalo1_n >=0 & floor(numero_clientes_intervalo1_n)==numero_clientes_intervalo1_n &...
      ceil(numero_clientes_intervalo1_n)==numero_clientes_intervalo1_n & ...
	  numero_clientes_intervalo2_n >=0 & floor(numero_clientes_intervalo2_n)==numero_clientes_intervalo2_n &...
	  ceil(numero_clientes_intervalo2_n)==numero_clientes_intervalo2_n & ...
   	  numero_clientes_intervalo2_n>numero_clientes_intervalo1_n & ...          
   	  numero_clientes_intervalo2_n<clientes_cerradas &...
      numero_nodo_intervalo_dibujar_n>0 & numero_nodo_intervalo_dibujar_n<=nodos_cerradas & ...
      numero_nodo_intervalo_dibujar_n==floor(numero_nodo_intervalo_dibujar_n) &...
      numero_nodo_intervalo_dibujar_n==ceil(numero_nodo_intervalo_dibujar_n))
   
   
   	if (cambiar_parametros_redes_cerradas==2)      
         delete(dibujo3)
    end         
      
    cambiar_parametros_redes_cerradas=2;
   
	   
   	dibujo3=axes('Position', [0.5 0.42 0.3 0.19]);

    bar(numero_clientes_intervalo1_n:numero_clientes_intervalo2_n, ...
    matriz_p_clientes_cerradas(numero_nodo_intervalo_dibujar_n,numero_clientes_intervalo1_n+1:numero_clientes_intervalo2_n+1))
    title('Grafica de p(i)')           

   	      
else
   text_redes_cerradas_intervalo_error = uicontrol(gcf, 'Style', 'Text', ...
       'String', 'Error en los parametros', ...
       'Units', 'normalized', ...
       'Position', [0.15 0.58  0.2 0.03], ...
       'FontUnits', 'normalized', ...
       'FontWeight', 'bold', ...
       'FontSize', 0.5, ...
       'ForegroundColor', 'r', ...
	   'BackgroundColor', [.6 .6 .6],...
       'HorizontalAlignment', 'Center');
end   



