% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  dibujar_p_simulacion.m

%Calcula el valor de p(i) de un modelo G/G/... en un intervalo de valores
% y lo muesta en un diagrama de barras

%Recibe el valor de los indices que forman el intervalo

indice_1_n = get(indice_1, 'String');
indice_1_n = str2num(indice_1_n);

indice_2_n = get(indice_2, 'String');
indice_2_n = str2num(indice_2_n);



%Comprueba que el valor de los indices es mayor o igual a cero y
%que el segundo indice es mayor que el primero

if (indice_1_n>=0 & indice_2_n>0 & indice_2_n>indice_1_n)
   
   %Comprueba que los indices son numeros enteros

	if (ceil(indice_1_n) == indice_1_n & floor(indice_1_n) == indice_1_n & ...
       ceil(indice_2_n) == indice_2_n & floor(indice_2_n) == indice_2_n)
    
    %Comprueba que los indices no se salen de rango en funcion del 
    %modelo de colas que se desea resolver

    if(eleccion == 1 | eleccion == 2 | (eleccion == 3 & indice_2_n<=k_n+1) | ...
          (eleccion ==4 & indice_2_n<=k_n+s_n) | ...
          (eleccion ==5 & indice_2_n<=h_n) | ...
          (eleccion ==6 & indice_2_n<=h_n) | ...
          (eleccion ==7 & indice_2_n<=y_n+h_n) | ...
          eleccion ==8)
       
	      for i=length(p):indice_2_n+1
   	         p(i+1)=0;
          end
       
         text_dibujar_p_error = uicontrol(gcf, 'Style', 'Text', ...
 		   'String', '', ...
   		   'Units', 'normalized', ...
           'Position', [0.155 0.455 0.3 0.03], ...
           'ForegroundColor', 'r', ...
           'BackgroundColor', [0.6 0.6 0.6], ...
	   	   'FontUnits', 'normalized', ...
	   	   'FontSize', 0.2, ...
           'HorizontalAlignment', 'Center');
      
        
		 global dibujo2;

                   
                  
         %Borra el dibujo anterior (en caso de que exista), para crear uno 
         %nuevo que no sobreescriba el anterior
                 
 		 if (cambiar_parametros_mm==2)      
             delete(dibujo2)
         end
         
         cambiar_parametros_mm=2;
         
         
         %indices es un vector indice1, indice1+1, ..., indice2
         indices=linspace(indice_1_n,indice_2_n,indice_2_n-indice_1_n+1);
         
         
         p_varios=p(indices+1);
   
            
      %Dibuja el diagrama de barras correspondiente   
      
		dibujo2=axes('Position', [0.54 0.39 0.3 0.3]);

		bar(indice_1_n:indice_2_n,p_varios)
        title('Grafica de p(i)')           
      
  	 else
                      
        text_dibujar_p_error = uicontrol(gcf, 'Style', 'Text', ...
 		 'String', 'Error en los parametros', ...
   		 'Units', 'normalized', ...
         'Position', [0.155 0.455 0.3 0.03], ...
         'BackgroundColor', [0.6 0.6 0.6], ...
         'ForegroundColor', 'r', ...
	     'FontUnits', 'normalized', ...
         'FontWeight', 'bold', ...
	   	 'FontSize', 0.5, ...
         'HorizontalAlignment', 'Center');
      
   
	  end

	else
                                      
        text_dibujar_p_error = uicontrol(gcf, 'Style', 'Text', ...
 		 'String', 'Error en los parametros', ...
   		 'Units', 'normalized', ...
         'Position', [0.155 0.455 0.3 0.03], ...
         'BackgroundColor', [0.6 0.6 0.6], ...
         'ForegroundColor', 'r', ...
	   	 'FontUnits', 'normalized', ...
         'FontWeight', 'bold', ...
	   	 'FontSize', 0.5, ...
         'HorizontalAlignment', 'Center');

	end

else
        
     
	  text_dibujar_p_error = uicontrol(gcf, 'Style', 'Text', ...
 		 'String', 'Error en los parametros', ...
   		 'Units', 'normalized', ...
         'Position', [0.155 0.455 0.3 0.03], ...
         'BackgroundColor', [0.6 0.6 0.6], ...
         'ForegroundColor', 'r', ...
	   	 'FontUnits', 'normalized', ...
         'FontWeight', 'bold', ...
	   	 'FontSize', 0.5, ...
         'HorizontalAlignment', 'Center');

end


