% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  info.m

% Muestra informacion de la aplicacion


% Se crea una nueva ventana

figure('Units', 'normalized',...
		'Position', [0.3 0.3 0.5 0.5],...
        'MenuBar', 'none', ...
        'name', 'Informacion de la aplicacion', ...
        'NumberTitle', 'off', ...
        'resize','off');

frame_info = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.702 .702 .702],...
   'Position', [0.2 0.11 0.6 0.82]);    
    
text_inicio = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'AQUAS', ...
   'Units', 'normalized', ...
   'Position', [0.40 0.83 0.2 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.8, ...
   'FontWeight', 'Bold', ...
   'FontAngle', 'Oblique', ...
   'FontName', 'Verdana', ...
   'ForegroundColor', [0 0 0.8], ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_iniciales = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Application for solving QUeuing problems Analytically and using Simulation', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.70 0.5 0.11], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.28, ...
   'FontWeight', 'Bold', ...
   'FontName', 'Verdana', ...
   'ForegroundColor', [0 0 0.8], ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_proyecto = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'PROYECTO DE FIN DE CARRERA DE INGENIERIA INFORMATICA', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.40 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.4, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_proyecto = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Depatamento de Matematicas', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.48 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.4, ...
   'FontAngle', 'italic', ...
   'FontName', 'Verdana', ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_proyecto = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Universidade de A Coruña', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.6 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.4, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_autor = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Autor: Jorge L. Vega Valle', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.25 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.36, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Left');

text_info_autor = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'FACULTAD DE INFORMATICA', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.56 0.5 0.04], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.36, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

text_info_director = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Director: Ricardo Cao Abad', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.19 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.36, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Left');

text_info_director = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'Enero de 2004', ...
   'Units', 'normalized', ...
   'Position', [0.58 0.19 0.2 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.36, ...
   'FontWeight', 'Bold', ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Right');

%text_info_descargar = uicontrol(gcf, 'Style', 'Text', ...
%   'String', 'Descargar en: ', ...
%   'Units', 'normalized', ...
%   'Position', [0.25 0.12 0.2 0.07], ...
%   'FontUnits', 'normalized', ...
%   'FontSize', 0.36, ...
%   'FontWeight', 'Bold', ...
%   'BackgroundColor', [.702 .702 .702],...
%   'HorizontalAlignment', 'Left');

text_info_url = uicontrol(gcf, 'Style', 'Text', ...
   'String', 'www.udc.es/dep/mate/teoriacolas/colas.htm', ...
   'Units', 'normalized', ...
   'Position', [0.25 0.12 0.5 0.07], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.36, ...
   'FontWeight', 'Bold', ...
   'ForegroundColor', [0 0 0.8], ...
   'BackgroundColor', [.702 .702 .702],...
   'HorizontalAlignment', 'Center');

boton_cerrar = uicontrol(gcf, 'Style', 'Pushbutton',...
   'String', 'X', 'Value', 0, ...
   'Units', 'normalized', ...
   'Position', [0.74 0.86 0.05 0.05], ...
   'FontUnits', 'normalized', ...
   'FontSize', 0.7, ...
   'Callback', 'cerrar_ventana');