% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  leer_parametros_simulacion_abiertas.m

%Lee los parametros de entrada para la simulacion de una red Abierta


close(1)

figure('Units', 'normalized',...
		  'Position', [0.05 0.05 0.9 0.9],...
          'MenuBar', 'none', ...
          'name', 'Resolucion por simulacion: Parametros de entrada de la red de Jackson abierta', ...
          'NumberTitle', 'off', ...
          'resize','off');

frame_parametros_distribucion_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.702 .702 .702],...
   'Position', [0.1 0.2 0.8 0.8]);     
     
frame_parametros_distribucion_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.28 0.8 0.4 0.17]);

frame_parametros_distribucion_3 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.25 0.23 0.46 0.5]);



text_param_distrib_1 = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Parametros de la distribucion', ...
	    'Units', 'normalized', ...
   	    'Position', [0.3 0.9 0.36 0.05], ...
	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold',...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');
   
   
text_entrada = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Distribucion de llegada:', ...
	    'Units', 'normalized', ...
   	    'Position', [0.28 0.65 0.2 0.05], ...
	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold',...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');
    
  
   
switch(distrib_entrada)
   
	case 1,
      texto1='Exponencial';
      
   case 2,
      texto1='Uniforme';
      
  case 3,
      texto1='Deterministica';
      
  case 4,
      texto1='Gamma';
      
  case 5,
      texto1='Beta';
      
  case 6,
      texto1='Lognormal';
      
  case 7,
      texto1='Normal';
      
  case 8,
      texto1='Weibull';
      
  case 9,
      texto1='No Entrada';
      
end
   
text_entrada_2 = uicontrol(gcf, 'Style', 'Text', ...
 	'String', texto1, ...
    'Units', 'normalized', ...
  	'Position', [0.53 0.65 0.15 0.05], ...
    'BackgroundColor', [.6 .6 .6],...
    'FontUnits', 'normalized', ...
    'FontWeight', 'bold',...
   	'FontSize', 0.4, ...
    'HorizontalAlignment', 'Center');   


switch (distrib_entrada)
   
  case 1, %Exponencial
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Lambda = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
  if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
  case 2, %Uniforme
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'b = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
         'String', num2str(parametros_entrada(pasos,1)), ...
   		 'Units', 'normalized', ...
		 'Position', [0.55 0.595 0.08 0.04], ...
         'FontUnits', 'normalized', ...
   	     'FontSize', 0.5, ...
		 'BackgroundColor', [.702 .702 .702],...
         'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
   
   case 3, %Deterministica
       
     text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'd = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
     if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
  case 4, %Gamma                                     
       
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
   if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
  case 5, %Beta
                                            
       
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'q = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.53 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
 
     text_parametro_3 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Escala = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.47 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
     if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end

  
     if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.535 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.535 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
           'HorizontalAlignment', 'Center');
      end
   
   
     if (cambiar_parametros_mm==0)
		par_ent_3 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.475 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_ent_3 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,3)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.475 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

   
   
  case 6, %Lognormal                                   
       
     text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
    if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end   
   

case 7, %Normal                                     
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
    		'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
    if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
         par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end
   
  case 8, %Weibull                                     
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	   'String', 'Lambda = ', ...
       'Units', 'normalized', ...
       'Position', [0.3 0.59 0.25 0.05], ...
       'BackgroundColor', [.6 .6 .6],...
       'FontUnits', 'normalized', ...
   	   'FontSize', 0.4, ...
       'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Alfa = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
  if (cambiar_parametros_mm==0)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm==0)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
             'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_entrada(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
end
   
   
   
   
   
   
   
   
   
text_salida = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Distribucion de servicio:', ...
	    'Units', 'normalized', ...
   	    'Position', [0.28 0.42 0.2 0.05], ...
	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');   
   

switch(distrib_salida)
   
	case 1,
      texto2='Exponencial';
      
   case 2,
      texto2='Uniforme';
      
  case 3,
      texto2='Deterministica';
      
  case 4,
      texto2='Gamma';
      
  case 5,
      texto2='Beta';
      
  case 6,
      texto2='Lognormal';
      
  case 7,
      texto2='Normal';
      
  case 8,
      texto2='Weibull';
         
      
end
   
   


text_salida_2 = uicontrol(gcf, 'Style', 'Text', ...
   	'String', texto2, ...
    'Units', 'normalized', ...
   	'Position', [0.53 0.42 0.15 0.05], ...
    'BackgroundColor', [.6 .6 .6],...
    'FontUnits', 'normalized', ...
    'FontWeight', 'bold', ...
   	'FontSize', 0.4, ...
    'HorizontalAlignment', 'Center');   
   
   
   
   
   
   
   
switch (distrib_salida)
   
  case 1, %Exponencial
     text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
     if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end
   
  case 2, %Uniforme
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'b = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
     if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end
   
      
      
  case 3, %Deterministica
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'd = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
      	    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end   
   

  case 4, %Gamma
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
    if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end
   

  case 5, %Beta
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'q = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.30 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
 
     text_parametro_3 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Escala = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.24 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
   if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.305 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.305 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end
   
     if (cambiar_parametros_mm==0)
		par_sal_3 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.245 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
      par_sal_3 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,3)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.245 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
  case 6, %LogNormal
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
   if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

   
  case 7, %Normal
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
    if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end
   

  case 8, %Weibull
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Lambda = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Alfa = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm==0)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,1)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm==0)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(parametros_salida(pasos,2)), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
end







%Llama a redes_abiertas para leer los parametros de otro nodo de la red   

   

boton_param_distribu_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
   	    'String', 'Siguiente >>', 'Value', 0, ...
        'Units', 'normalized', ...
        'Position', [0.38 0.05 0.2 0.1], ...
        'FontUnits', 'normalized', ...
        'Fontweight', 'bold', ...
   	    'FontSize', 0.2, ...
        'Callback', 'comprobar_parametros_abiertas');
