% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  parametros_distribucion.m

% Lee los parametros de la distribucion


if(estoy_en_redes_abiertas ~= 1)
   
   %En todos los modelos hay que recibir los valores de estabilizacion y clientes a simular
	estab_n = get(estab, 'String');
	estab_n = str2num(estab_n);

	cli_sim_n = get(cli_sim, 'String');
	cli_sim_n = str2num(cli_sim_n);

   
	%Modelos M/M/s, M/M/s/K, M/M/s/inf/H, M/M/s/inf/H con Y repuestos (recibir s)
	if (eleccion == 2| eleccion == 4| eleccion ==6| eleccion==7)
   	   s_n = get(s, 'String');
	   s_n = str2num(s_n);
	end

	%Modelos M/M/1/K, M/M/s/K (recibir k)
	if (eleccion == 3| eleccion == 4)
       k_n = get(k, 'String');
	   k_n = str2num(k_n);
	end

	%Modelos M/M/1/inf/H, M/M/s/inf/H, M/M/s/inf/H con Y repuestos (recibir h)
	if (eleccion == 5| eleccion == 6 | eleccion ==7)
       h_n = get(h, 'String');
	   h_n = str2num(h_n);
	end

	%Modelo M/M/s/inf/H con Y repuestos (recibir y)
	if (eleccion == 7)
       y_n = get(y, 'String');
	   y_n = str2num(y_n);
   end
end



%Si los parametros son correctos se abre una nueva ventana con
%los parametros de salida

if ((estab_n>0 & cli_sim_n>0 & floor(estab_n)==estab_n & ceil(estab_n)==estab_n & floor(cli_sim_n)==cli_sim_n & ceil(cli_sim_n)==cli_sim_n) & (...
   (eleccion == 1) | ...
   (eleccion == 2 & s_n>=1 & floor(s_n)==s_n & ceil(s_n)==s_n) | ...
   (eleccion == 3 & k_n>=0 & floor(k_n)==k_n & ceil(k_n)==k_n) | ...
   (eleccion == 4 & s_n>=1 & k_n>=0 & floor(s_n)==s_n & ceil(s_n)==s_n & floor(k_n)==k_n & ceil(k_n)==k_n) | ...
   (eleccion == 5 & h_n>0 & floor(h_n)==h_n & ceil(h_n)==h_n) | ...
   (eleccion == 6 & s_n>=1 & h_n>0 & floor(s_n)==s_n & ceil(s_n)==s_n & floor(h_n)==h_n & ceil(h_n)==h_n) | ...
   (eleccion == 7 & s_n>=1 & h_n>0 & y_n>=0 & floor(s_n)==s_n & ceil(s_n)==s_n & floor(h_n)==h_n & ceil(h_n)==h_n & floor(y_n)==y_n & ceil(y_n)==y_n) | ...
   (eleccion == 8 )))

  % Cerramos la ventana anterior en donde introduciamos
  % los parametros de entrada de la simulacion del modelo
  % de colas


  if (estoy_en_redes_abiertas ~= 1)  
     close(1)
  end


  % Y abrimos una ventana nueva en donde se le va a
  % solicitar al usuario los parametros de entrada
  % segun el tipo de distribucion


  if (estoy_en_redes_abiertas ~=1)
	figure('Units', 'normalized',...
		   'Position', [0.05 0.05 0.9 0.9],...
           'MenuBar', 'none', ...
           'name', 'Resolucion por simulacion: Parametros de la distribucion', ...
           'NumberTitle', 'off', ...
           'resize','off');
   else
     	figure('Units', 'normalized',...
		  'Position', [0.1 0.1 0.8 0.8],...
          'resize','off');
   end



     
  frame_parametros_distribucion_1 = uicontrol(gcf, 'Style', 'Frame', ...
    'Units', 'normalized', ...
    'BackgroundColor', [.702 .702 .702],...
    'Position', [0.1 0.2 0.8 0.8]);     
     
  frame_parametros_distribucion_2 = uicontrol(gcf, 'Style', 'Frame', ...
    'Units', 'normalized', ...
    'BackgroundColor', [.6 .6 .6],...
    'Position', [0.28 0.8 0.4 0.17]);

  frame_parametros_distribucion_3 = uicontrol(gcf, 'Style', 'Frame', ...
    'Units', 'normalized', ...
	'BackgroundColor', [.6 .6 .6],...
    'Position', [0.25 0.23 0.46 0.5]);



  text_param_distrib_1 = uicontrol(gcf, 'Style', 'Text', ...
     	'String', 'Parametros de la distribucion', ...
	    'Units', 'normalized', ...
   	    'Position', [0.3 0.9 0.36 0.05], ...
	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold',...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');
   
   
  text_entrada = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Distribucion de llegada:', ...
	    'Units', 'normalized', ...
   	    'Position', [0.28 0.65 0.2 0.05], ...
	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold',...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');
   
  switch(distrib_entrada)
   
	case 1,
      texto1='Exponencial';
      
   case 2,
      texto1='Uniforme';
      
   case 3,
      texto1='Deterministica';
      
   case 4,
      texto1='Gamma';
      
   case 5,
      texto1='Beta';
      
   case 6,
      texto1='Lognormal';
      
   case 7,
      texto1='Normal';
      
   case 8,
      texto1='Weibull';
      
  end
   
  text_entrada_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', texto1, ...
        'Units', 'normalized', ...
  	    'Position', [0.53 0.65 0.15 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold',...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');   


  switch (distrib_entrada)
   
  case 1, %Exponencial
   text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Lambda = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

   
  case 2, %Uniforme
   text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'b = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
    if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end
   
   case 3, %Deterministica
       
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'd = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
     if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
       end
   
   case 4, %Gamma                                     
       
   text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
             'HorizontalAlignment', 'Center');
     else
        par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
   if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
       	    'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
  case 5, %Beta
                                            
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'q = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.53 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
 
    text_parametro_3 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Escala = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.47 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
     if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.535 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.535 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
    	    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end
   
   
     if (cambiar_parametros_mm~=1)
		par_ent_3 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.475 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      else
         par_ent_3 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_3_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.475 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
       end

   
   
  case 6, %Lognormal                                   
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
    	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
   if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
       	    'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end   
   

  case 7, %Normal                                     
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
        par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

  
   if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   case 8, %Weibull                                     
       
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Lambda = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.59 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Alfa = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.5 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
  if (cambiar_parametros_mm~=1)
		par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.595 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
   if (cambiar_parametros_mm~=1)
		par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_ent_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_ent_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.505 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
end
   
   
   
   
   
   
   
   
   
text_salida = uicontrol(gcf, 'Style', 'Text', ...
   	'String', 'Distribucion de servicio:', ...
	'Units', 'normalized', ...
   	'Position', [0.28 0.42 0.2 0.05], ...
	'BackgroundColor', [.6 .6 .6],...
    'FontUnits', 'normalized', ...
    'FontWeight', 'bold', ...
   	'FontSize', 0.4, ...
    'HorizontalAlignment', 'Center');   
   

switch(distrib_salida)
   
	case 1,
      texto2='Exponencial';
      
   case 2,
      texto2='Uniforme';
      
  case 3,
      texto2='Deterministica';
      
  case 4,
      texto2='Gamma';
      
  case 5,
      texto2='Beta';
      
  case 6,
      texto2='Lognormal';
      
  case 7,
      texto2='Normal';
      
  case 8,
      texto2='Weibull';
         
      
end
   
   


text_salida_2 = uicontrol(gcf, 'Style', 'Text', ...
   	'String', texto2, ...
	'Units', 'normalized', ...
   	'Position', [0.53 0.42 0.15 0.05], ...
	'BackgroundColor', [.6 .6 .6],...
    'FontUnits', 'normalized', ...
    'FontWeight', 'bold', ...
   	'FontSize', 0.4, ...
    'HorizontalAlignment', 'Center');   
   
   
   
   
   
   
   
switch (distrib_salida)
   
  case 1, %Exponencial
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end
   
  case 2, %Uniforme
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'b = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   	    	'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   
   
  case 3, %Deterministica
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'd = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end   
   

  case 4, %Gamma
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'a = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   	    	'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   

  case 5, %Beta
    
  text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'p = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
   text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'q = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.30 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
 
   text_parametro_3 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Escala = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.24 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end

  
     if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.305 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
        par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.305 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     end
   
     if (cambiar_parametros_mm~=1)
		par_sal_3 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.245 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_sal_3 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_3_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.245 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
           'HorizontalAlignment', 'Center');
      end
   
      
  case 6, %LogNormal
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
    	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   	     	'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
            'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
   if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

   
  case 7, %Normal
      
   text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Mu = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Sigma = ', ...
        'Units', 'normalized', ...
      	'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
  if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
       		'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end

  
  if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   else
      par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
   end
   

   
  case 8, %Weibull
    text_parametro_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Lambda = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.36 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    text_parametro_2 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Alfa = ', ...
        'Units', 'normalized', ...
  	    'Position', [0.3 0.27 0.25 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized', ...
   	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Left');   
  
    if (cambiar_parametros_mm~=1)
		par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
       par_sal_1 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_1_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.365 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
      end

  
    if (cambiar_parametros_mm~=1)
		par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
           	'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
     else
       par_sal_2 = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(par_sal_2_n), ...
   		    'Units', 'normalized', ...
			'Position', [0.55 0.275 0.08 0.04], ...
            'FontUnits', 'normalized', ...
   	        'FontSize', 0.5, ...
		    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end
   
   
  end
   
   
   boton_param_distribu_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
   	    'String', 'Siguiente >>', 'Value', 0, ...
     	'Units', 'normalized', ...
     	'Position', [0.38 0.05 0.2 0.1], ...
        'FontUnits', 'normalized', ...
        'Fontweight', 'bold', ...
   	    'FontSize', 0.2, ...
        'Callback', 'salida_distribucion');

   
   
   
else 
   
   text_errores = uicontrol(gcf, 'Style', 'Text', ...
		    'Units', 'normalized', ...
		    'String', 'ERROR EN LOS PARAMETROS', ...
            'Position', [0.35 0.74 0.30 0.04], ...
		    'BackgroundColor', [.702 .702 .702],...   
            'ForegroundColor', 'r',...
            'FontUnits', 'normalized', ...
            'FontWeight', 'bold', ...
        	'FontSize', 0.4, ...		  
		    'HorizontalAlignment', 'Center');


end


   
