% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  redes_abiertas_no_estacionario.m

%Este fichero se encarga de hacer notar al usuario que
%la red de Jackson no es estacionario segun los parametros
%de entrada que el ha seleccionado.

%Cerramos la ventana anterior y creamos una nueva

close(1)

figure('Units', 'normalized',...
        'Position', [0.05 0.05 0.9 0.9],...
        'MenuBar', 'none', ...
        'name', 'Resolucion analitca: Red de Jackson abierta no estacionaria', ...
        'NumberTitle', 'off', ...
        'resize','off');
     
frame_no_estacionario_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.702 .702 .702],...
   'Position', [0.1 0.2 0.8 0.8]);     
     
frame_no_estacionario_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.28 0.8 0.4 0.17]);

%Indicamos que el sistema no es estacionario

text_no_estacionario_1 = uicontrol(gcf, 'Style', 'Text', ...
     	'String', 'Redes de Jackson Abiertas', ...
       	'Units', 'normalized', ...
        'Position', [0.3 0.9 0.36 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
	    'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
        'FontSize', 0.5, ...
   	    'HorizontalAlignment', 'Center');

text_no_estacionario = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'El sistema no es estacionario', ...
   	    'Units', 'normalized', ...
		'Position', [0.23 0.5 0.5 0.05], ...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
        'FontSize', 0.5, ...
        'ForegroundColor', 'r',...
		'BackgroundColor', [.702 .702 .702],...
        'HorizontalAlignment', 'Center');

%Si el usuario hace click en siguiente, se ejecuta el 
%contenido del fichero aquas.

boton_redes_abiertas_no_estacionario_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
        'String', 'Menu Inicio >>', 'Value', 0, ...
        'Units', 'normalized', ...
        'Position', [0.2 0.05 0.2 0.07], ...
        'FontUnits', 'normalized', ...
        'FontSize', 0.3, ...
        'Callback', 'aquas');



boton_redes_abiertas_no_estacionario_salida_cambiar_parametros = uicontrol(gcf, 'Style', 'Pushbutton',...
        'String', 'Cambiar los parametros del problema >>', 'Value', 0, ...
        'Units', 'normalized', ...
        'Position', [0.5 0.05 0.3 0.07], ...
        'FontUnits', 'normalized', ...
        'FontSize', 0.3, ...
        'Callback', 'cambiar_parametros_abiertas');


