% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  redes_abiertas_salida.m

%Este fichero se encarga de mostrar los parametros de salida
%de la red:
%1.-El valor de L, Lq, W, Wq en cada nodo.
%2.-El valor de LT, LqT, WT y WqT.
%3.-La probabilidad de que haya un determinado numero de usuarios
%en la red


%Cerramos la ventana anterior y creamos una nueva.

close(1)

figure('Units', 'normalized',...
		  'Position', [0.05 0.05 0.9 0.9],...
          'MenuBar', 'none', ...
          'name', 'Resolucion analitica: Resultados de la red de Jackson abierta', ...
          'NumberTitle', 'off', ...
          'resize','off');
     
frame_redes_abiertas_salida_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.85 0.82 0.13]);     
     
frame_redes_abiertas_salida_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.35 0.82 0.48]);

frame_redes_abiertas_salida_3 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.16 0.82 0.17]);

texto_cabecera_redes_abiertas='Resultados globales ( ';
texto_cabecera_redes_abiertas=strcat(texto_cabecera_redes_abiertas, num2str(nodos_abiertas), ' Nodos)');

text_redes_abiertas_salida_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', texto_cabecera_redes_abiertas, ...
   	    'Units', 'normalized', ...
	    'Position', [0.35 0.92 0.3 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.4, ...
   	    'HorizontalAlignment', 'Center');
   
text_redes_abiertas_salida_lt_1 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'LT = ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.12 0.86 0.08 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');   
   
text_redes_abiertas_salida_lqt_1 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'LqT = ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.32 0.86 0.08 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');   
   
text_redes_abiertas_salida_wt_1 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'WT = ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.52 0.86 0.08 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');   

text_redes_abiertas_salida_wqt_1 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'WqT = ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.72 0.86 0.08 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');  
   
%Calcula el valor de Lq en cada nodo, asi como el valor de L en cada nodo
for i=1:nodos_abiertas
   
   %La funcion resolver_mms, se encarga de averiguar cual es el valor de L,
   %en un modelo M/M/s, y se le pasan como parametros el numero de servidores,
   %el valor de lambda y el valor de mu
   lq_abiertos(i)=resolver_mms(vector_servidores_abiertas(i),lambda_mayuscula(i),vector_mu_abiertas(i));
   
   l_abiertos(i)=lq_abiertos(i)+lambda_mayuscula(i)/vector_mu_abiertas(i);
   
end


%Muestra los valores de L, Lq, W y Wq en cada nodo

for i=1:nodos_abiertas
         
   texto_abiertas=strcat('Nodo nº ',' ',num2str(i));

   text_redes_abiertas_salida = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', texto_abiertas, ...
   	    'Units', 'normalized', ...
		'Position', [0.12 0.83-0.48*i/(nodos_abiertas+1) 0.1 0.05], ...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.3, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');   
         
	text_redes_abiertas_salida_l_1 = uicontrol(gcf, 'Style', 'Text', ...
            'String', 'L = ', ...
   	        'Units', 'normalized', ...
	        'Position', [0.25 0.83-0.48*i/(nodos_abiertas+1) 0.05 0.05], ...
       	    'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');   
   
    aux=num2str(l_abiertos(i));
   
  	text_redes_abiertas_salida_l_2 = uicontrol(gcf, 'Style', 'Text', ...
            'String', aux, ...
   	        'Units', 'normalized', ...
	        'Position', [0.30 0.83-0.48*i/(nodos_abiertas+1) 0.10 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
   	        'HorizontalAlignment', 'Center');   
   
   
   
	text_redes_abiertas_salida_lq_1 = uicontrol(gcf, 'Style', 'Text', ...
            'String', 'Lq = ', ...
   	        'Units', 'normalized', ...
	        'Position', [0.4 0.83-0.48*i/(nodos_abiertas+1) 0.05 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
   	        'HorizontalAlignment', 'Center');   
   
   aux=num2str(lq_abiertos(i));
   
  	text_redes_abiertas_salida_lq_2 = uicontrol(gcf, 'Style', 'Text', ...
            'String', aux, ...
   	        'Units', 'normalized', ...
	        'Position', [0.45 0.83-0.48*i/(nodos_abiertas+1) 0.10 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');   
   
   
	text_redes_abiertas_salida_w_1 = uicontrol(gcf, 'Style', 'Text', ...
            'String', 'W = ', ...
   	        'Units', 'normalized', ...
	        'Position', [0.55 0.83-0.48*i/(nodos_abiertas+1) 0.05 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');   
   
   aux=num2str(lq_abiertos(i)/lambda_mayuscula(i)+1/vector_mu_abiertas(i));
   
  	text_redes_abiertas_salida_w_2 = uicontrol(gcf, 'Style', 'Text', ...
            'String', aux, ...
   	        'Units', 'normalized', ...
	        'Position', [0.6 0.83-0.48*i/(nodos_abiertas+1) 0.10 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');   


   
	text_redes_abiertas_salida_wq_1 = uicontrol(gcf, 'Style', 'Text', ...
            'String', 'Wq = ', ...
   	        'Units', 'normalized', ...
	        'Position', [0.7 0.83-0.48*i/(nodos_abiertas+1) 0.05 0.05], ...
            'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');  
   
   aux=num2str(lq_abiertos(i)/lambda_mayuscula(i));
   
  	text_redes_abiertas_salida_wq_2 = uicontrol(gcf, 'Style', 'Text', ...
            'String', aux, ...
   	        'Units', 'normalized', ...
	        'Position', [0.75 0.83-0.48*i/(nodos_abiertas+1) 0.10 0.05], ...
   	        'BackgroundColor', [.6 .6 .6],...
            'FontUnits', 'normalized',...
	        'FontSize', 0.3, ...
            'HorizontalAlignment', 'Center');   
   
   
   informacion_nodo='Lambda mayuscula = ';
   informacion_nodo=strcat(informacion_nodo, ' ',num2str(lambda_mayuscula(i)));
   
   informacion_nodo=strcat(informacion_nodo, ', Mu = ',num2str(vector_mu_abiertas(i)));
   
   informacion_nodo=strcat(informacion_nodo, ', s = ',num2str(vector_servidores_abiertas(i)));
   
   text_informacion_nodo = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', informacion_nodo, ...
   	    'Units', 'normalized', ...
		'Position', [0.12 0.8-0.48*i/(nodos_abiertas+1) 0.5 0.05], ...
        'FontUnits', 'normalized',...
	    'FontSize', 0.2, ...
        'ForegroundColor', 'b',...
        'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Left');   
  


end


estoy_en_redes_abiertas=1;
   
eleccion=2;
      

   
text_informacion = uicontrol(gcf, 'Style', 'Text', ...
  	'String', 'Introduce el numero del nodo del cual deseas obtener informacion mas detallada ', ...
  	'Units', 'normalized', ...
	'Position', [0.12 0.36 0.45 0.05], ...
 	'BackgroundColor', [.6 .6 .6],...
    'FontUnits', 'normalized',...
	'FontSize', 0.3, ...
    'HorizontalAlignment', 'Center');   

nodo = uicontrol(gcf, 'Style', 'Edit', ...
   'Units', 'normalized', ...
   'Position', [0.6 0.36 0.05 0.05], ...
   'BackgroundColor', [.702 .702 .702],...
   'FontUnits', 'normalized',...
   'FontSize', 0.3, ...
   'HorizontalAlignment', 'Center');


boton_informacion = uicontrol(gcf, 'Style', 'Pushbutton', ...
  	'String', 'OK ', ...
  	'Units', 'normalized', ...
	'Position', [0.66 0.36 0.05 0.05], ...
    'FontUnits', 'normalized',...
	'FontSize', 0.3, ...
    'Callback', 'detalles_nodo');





aux=sum(l_abiertos);

%Muestra el valor de LT, LqT, WT, WqT

text_redes_abiertas_salida_lt_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', aux, ...
   	    'Units', 'normalized', ...
	    'Position', [0.2 0.86 0.12 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');   
   
aux=sum(lq_abiertos);
   
text_redes_abiertas_salida_lqt_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', aux, ...
   	    'Units', 'normalized', ...
	    'Position', [0.4 0.86 0.12 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');   
   
aux=sum(l_abiertos)/suma_lambda_abiertas;   
   
text_redes_abiertas_salida_wt_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', aux, ...
   	    'Units', 'normalized', ...
	    'Position', [0.6 0.86 0.12 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');   
   
aux=sum(lq_abiertos)/suma_lambda_abiertas;   
   
text_redes_abiertas_salida_wqt_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', aux, ...
   	    'Units', 'normalized', ...
	    'Position', [0.8 0.86 0.11 0.05], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');  
   
 text_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'Probabilidad de un determinado numero de clientes en cada nodo:', ...
   	    'Units', 'normalized', ...
	    'Position', [0.2 0.29 0.65 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
   
%Tambien se puede averiguar la probabilidad de que haya un determinado
%numero de elementos en cada nodo de la red.

%En este bucle se lee el valor del numero de elementos presente en cada
%nodo de la red.
   
for i=1:nodos_abiertas
         
   texto_abiertas=num2str(i);

	text_redes_abiertas_salida_nodo = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', texto_abiertas, ...
   	    'Units', 'normalized', ...
		'Position', [0.10+0.72*i/(nodos_abiertas+1) 0.245   0.02 0.03], ...
        'FontUnits', 'normalized',...
	    'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
   elementos(i) = uicontrol(gcf, 'Style', 'Edit', ...
   	    'Units', 'normalized', ...
		'Position', [0.13+0.72*i/(nodos_abiertas+1) 0.245   0.05 0.04], ...
        'FontUnits', 'normalized',...
	    'FontSize', 0.4, ...
		'BackgroundColor', [.702 .702 .702],...
        'HorizontalAlignment', 'Center');

end

clear lq_abiertos;
clear l_abiertos;
clear texto_abiertas;
clear aux;

%Una vez leido el valor del numero de elementos en cada nodo de la red, para
%calcular la probabilidad se llama al fichero calcular_p_abiertas

boton_redes_abiertas_salida_calcular = uicontrol(gcf, 'Style', 'Pushbutton',...
    'String', 'Calcular', 'Value', 0, ...
    'Units', 'normalized', ...
    'Position', [0.43 0.18 0.1 0.04], ...
    'FontUnits', 'normalized',...
	'FontSize', 0.4, ...
    'Callback', 'calcular_p_abiertas'); 

%Si se hace click en siguiente, se ejecuta el contenido del fichero llamado
%aquas

cambiar_parametros_mm=0;

boton_redes_abiertas_salida_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Menu Inicio >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.2 0.05 0.2 0.07], ...
  'FontUnits', 'normalized',...
  'FontSize', 0.3, ...
  'Callback', 'aquas');

boton_redes_abiertas_salida_cambiar_parametros = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Cambiar los parametros del problema >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.5 0.05 0.3 0.07], ...
  'FontUnits', 'normalized',...
  'FontSize', 0.3, ...
  'Callback', 'cambiar_parametros_abiertas');

