% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  redes_cerradas.m

%Este fichero se encarga de leer el valor de mu
%y numero de servidores para cada nodo que forma la red.
%Tambien se encarga de leer el valor de las probabilidades
%desde cada nodo de la red a todos los restantes.


%Cerramos la ventana anterior (en un primer caso, es la que
%pregunta sobre el numero de nodos de la red, mientras que 
%en un segundo caso pregunta sobre los parametros de entrada
%de un determinado nodo de la red de Jackson cerrada).

if (pasos ==0 & variable ==0)

	clientes_cerradas = get(clientes_cerradas_n, 'String');
   clientes_cerradas = str2num(clientes_cerradas);
   
   clientes_cerradas = clientes_cerradas+1;
   
   %Si hay 0 clientes, clientes_cerradas vale 1, 
   %Si hay 1 clientes, clientes_cerradas vale 2 
	%Si hay 2 clientes, clientes_cerradas vale 3... 

   
end

%No hay error si hay 2 o mas clientes (clientes_cerradas>=3)
%y si es un numero entero...

if (clientes_cerradas>=3 & ceil(clientes_cerradas)==clientes_cerradas & ...
   floor(clientes_cerradas)==clientes_cerradas)

close(1)

figure('Units', 'normalized',...
		'Position', [0.05 0.05 0.9 0.9],...
        'MenuBar', 'none', ...
        'name', 'Resolucion analitica: Parametros de entrada de la red de Jackson cerrada', ...
        'NumberTitle', 'off', ...
        'resize','off');
     
     
%Nos encontramos en el primer nodo y el la primera vez que
%pasamos por el

if (pasos == 0 & variable == 0)
   nodos_cerradas=nodos_cerradas+1;
   variable=variable+1;
end
     
     
pasos = pasos +1;  

frame_redes_cerradas_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.78 0.8 0.2]);     

frame_redes_cerradas_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.2 0.8 0.55]);     


texto1=strcat('Nodo nº ',' ',num2str(pasos));

text_redes_cerradas_1 = uicontrol(gcf, 'Style', 'Text', ...
   	'String', texto1, ...
   	'Units', 'normalized', ...
	'Position', [0.4 0.91 0.25 0.05], ...
   	'FontUnits', 'normalized', ...
    'FontWeight', 'bold', ...
    'FontSize', 0.5, ...
    'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');
   
%Leer mu
text_redes_cerradas_mu = uicontrol(gcf, 'Style', 'Text', ...
   	'String', 'Mu = ', ...
   	'Units', 'normalized', ...
	'Position', [0.25 0.8 0.05 0.05], ...
   	'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
    'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center'); 
   
mu_cerradas = uicontrol(gcf, 'Style', 'Edit', ...
   	'Units', 'normalized', ...
	'Position', [0.32 0.8 0.08 0.05], ...
   	'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
	'BackgroundColor', [.702 .702 .702],...
    'HorizontalAlignment', 'Center');


%Leer numero de servidores
text_redes_cerradas_servidores = uicontrol(gcf, 'Style', 'Text', ...
   	'String', 'Servidores = ', ...
   	'Units', 'normalized', ...
    'Position', [0.55 0.8 0.15 0.05], ...
   	'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
	'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');  
   
servidores_cerradas = uicontrol(gcf, 'Style', 'Edit', ...
   	'Units', 'normalized', ...
	'Position', [0.72 0.8 0.08 0.05], ...
   	'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
    'BackgroundColor', [.702 .702 .702],...
    'HorizontalAlignment', 'Center');
   
%Leer el valor de la probabilidad de ir de un determinado nodo de la
%red de Jackson a otro. A diferencia de las redes de Jackson abiertas
%la suma de todas las probabilidades para un determinado nodo, deben
%ser igual a uno.

for j=1:nodos_cerradas
   texto_probabilidad=strcat('Probabilidad de ir al nodo nº ',num2str(j));
   
   text_redes_cerradas_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', texto_probabilidad, ...
   	    'Units', 'normalized', ...
		'Position', [0.3 (0.75-0.55*(j/(nodos_cerradas+1))) 0.35 0.05], ...
      	'FontUnits', 'normalized', ...
        'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
         'HorizontalAlignment', 'Center');  
   
   prob_cerradas(j) = uicontrol(gcf, 'Style', 'Edit', ...
   	    'Units', 'normalized', ...
		'Position', [0.7 (0.75-0.55*(j/(nodos_cerradas+1))) 0.08 0.05], ...
        'FontUnits', 'normalized', ...
        'FontSize', 0.4, ...
	    'BackgroundColor', [.702 .702 .702],...
        'HorizontalAlignment', 'Center');

end      

clear texto1;

%Si se hace click en el boton de siguiente, se ejecuta el fichero 
%redes_cerradas_comprobar que se encarga de comprobar si los parametros
%introducidos son correctos. A su vez, el fichero redes_cerradas_comprobar
%volvera a llamar al fichero redes_cerradas mientras no se hayan leido
%los parametros de todos los nodos de la red

boton_redes_cerradas_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Siguiente >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.38 0.05 0.2 0.1], ...
  'FontUnits', 'normalized', ...
  'FontWeight', 'bold', ...
  'FontSize', 0.2, ...
  'Callback', 'redes_cerradas_comprobar');

else
   
   error_numero_clientes = uicontrol(gcf, 'Style', 'Text', ...
      'String', 'Error en el numero de clientes', ...
   	  'Units', 'normalized',...
	  'Value', 1 , ...
   	  'Position', [0.27 0.25 0.4 0.05], ...
      'FontUnits', 'normalized', ...
      'FontWeight', 'bold', ...
      'FontSize', 0.4, ...
      'ForegroundColor', 'r', ...
   	  'BackgroundColor', [.6 .6 .6], ...
	  'HorizontalAlignment', 'Center');
   
  
end


