% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  redes_abiertas_simulacion.m


%SUPOSICION IMPORTANTE !!!
%EN LAS REDES ABIERTAS SE ASUME QUE EL MODELO DE 
%LOS DISTINTOS ES EL G/G/s, A SECAS.



%Este fichero se encarga de leer el valor de lambda, mu
%y numero de servidores para cada nodo que forma la red.
%Tambien se encarga de leer el valor de las probabilidades
%desde cada nodo de la red a todos los restantes.


%Cerramos la ventana anterior (en un primer caso, es la que
%pregunta sobre el numero de nodos de la red, mientras que 
%en un segundo caso pregunta sobre los parametros de entrada
%de un determinado nodo de la red de Jackson abierta).

close(1)

figure('Units', 'normalized',...
		'Position', [0.05 0.05 0.9 0.9],...
        'MenuBar', 'none', ...
        'name', 'Resolucion por simulacion: Parametros de entrada de la red de Jackson abierta', ...
        'NumberTitle', 'off', ...
        'resize','off');
     
pasos = pasos + 1;

%Ya hemos leido los datos de todos los nodos que forman la red.
if (pasos > nodos_abiertas)
   
   
   for i=1:nodos_abiertas
      matriz_prob_abiertas(1,i)=1-sum(matriz_prob_abiertas(2:nodos_abiertas+1,i));
   end
   
   close(1)
   
   figure('Units', 'normalized',...
		  'Position', [0.05 0.05 0.9 0.9],...
          'MenuBar', 'none', ...
          'name', 'Resolucion por simulacion: Parametros de simulacion de la red de Jackson abierta', ...
          'NumberTitle', 'off', ...
          'resize','off');
      
   frame_redes_abiertas_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.78 0.8 0.2]);     

    frame_redes_abiertas_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.2 0.8 0.55]);     



    texto1='Parametros de simulacion';

    text_redes_abiertas_1 = uicontrol(gcf, 'Style', 'Text', ...
       	'String', texto1, ...
   	    'Units', 'normalized', ...
		'Position', [0.4 0.91 0.25 0.05], ...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
        'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
      
      
       
      
      
   text_estab = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Parametro de estabilizacion ', ...
       	'Units', 'normalized', ...
		'Position', [0.28 0.51 0.2 0.05], ...
   	    'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
    if (cambiar_parametros_mm==0)
		estab = uicontrol(gcf, 'Style', 'Edit', ...
   		'Units', 'normalized', ...
		'Position', [0.55 0.515 0.08 0.04], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.5, ...
		 'BackgroundColor', [.702 .702 .702],...
         'HorizontalAlignment', 'Center');
   else
      estab = uicontrol(gcf, 'Style', 'Edit', ...
         'String', num2str(estab_n), ...
  		'Units', 'normalized', ...
	    'Position', [0.55 0.515 0.08 0.04], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.5, ...
		 'BackgroundColor', [.702 .702 .702],...
         'HorizontalAlignment', 'Center');
    end
   
    text_cli_sim = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Numero clientes simulacion ', ...
       	'Units', 'normalized', ...
		'Position', [0.26 0.44 0.25 0.05], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
    if (cambiar_parametros_mm==0)
		cli_sim = uicontrol(gcf, 'Style', 'Edit', ...
   		'Units', 'normalized', ...
	    'Position', [0.55 0.445 0.08 0.04], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.5, ...
		 'BackgroundColor', [.702 .702 .702],...
         'HorizontalAlignment', 'Center');
   else
      cli_sim = uicontrol(gcf, 'Style', 'Edit', ...
         'String', num2str(cli_sim_n), ...
   		'Units', 'normalized', ...
	    'Position', [0.55 0.445 0.08 0.04], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.5, ...
	    'BackgroundColor', [.702 .702 .702],...
        'HorizontalAlignment', 'Center');
    end
   
   
    
        boton_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
   	        'String', 'Siguiente >>', 'Value', 0, ...
         	'Units', 'normalized', ...
         	'Position', [0.38 0.05 0.2 0.1], ...
            'FontUnits', 'normalized', ...
            'FontWeight', 'bold', ...
           	'FontSize', 0.2, ...
            'Callback', 'redes_abiertas_simulacion_salida');
       
  
     
         
else

     
     
frame_redes_abiertas_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.78 0.8 0.2]);     

frame_redes_abiertas_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.15 0.2 0.8 0.55]);     



texto1=strcat('Nodo nº ',' ',num2str(pasos));

text_redes_abiertas_1 = uicontrol(gcf, 'Style', 'Text', ...
       	'String', texto1, ...
   	    'Units', 'normalized', ...
		'Position', [0.4 0.91 0.25 0.05], ...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
        'FontSize', 0.5, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   

%Numero de servidores
text_redes_abiertas_servidores = uicontrol(gcf, 'Style', 'Text', ...
   	'String', 'Servidores = ', ...
   	'Units', 'normalized', ...
    'Position', [0.16 0.8 0.15 0.05], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
    'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');  

if (cambiar_parametros_mm==0)
    servidores_abiertas = uicontrol(gcf, 'Style', 'Edit', ...
   	'Units', 'normalized', ...
	'Position', [0.32 0.8 0.08 0.05], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
	'BackgroundColor', [.702 .702 .702],...
    'HorizontalAlignment', 'Center');
 else
    servidores_abiertas = uicontrol(gcf, 'Style', 'Edit', ...
    'String', num2str(vector_servidores_abiertas(pasos)), ...
   	'Units', 'normalized', ...
	'Position', [0.32 0.8 0.08 0.05], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
	'BackgroundColor', [.702 .702 .702],...
    'HorizontalAlignment', 'Center');
 end



text_tipo_distribucion = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Elegir tipo de distribucion ', ...
       	'Units', 'normalized', ...
		'Position', [0.5 0.85 0.25 0.05], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
    text_tipo_distribucion_entrada = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Llegada ', ...
       	'Units', 'normalized', ...
		'Position', [0.47 0.8 0.07 0.05], ...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
       	'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
    text_tipo_distribucion_salida = uicontrol(gcf, 'Style', 'Text', ...
   	    'String', 'Servicio ', ...
       	'Units', 'normalized', ...
		'Position', [0.70 0.8 0.07 0.05], ...
        'FontUnits', 'normalized', ...
        'FontWeight', 'bold', ...
       	'FontSize', 0.4, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');   

    
    if (cambiar_parametros_mm==0)   
    	distrib_entrada=1;
        distrib_salida=1;
    end


if (cambiar_parametros_mm==0)
 popup_distribucion_entrada = uicontrol(gcf, 'Style', 'PopupMenu', ...
       'String', 'Exponencial|Uniforme|Deterministica|Gamma|Beta|Lognormal|Normal|Weibull|No Entrada',...
        'Units', 'normalized',...
        'Value', distrib_entrada , ...
        'Position', [0.55 0.75 0.12 0.1], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.2, ...
       'BackgroundColor', [.702 .702 .702], ...
       'HorizontalAlignment', 'Center', ...
       'Callback', 'popup_distrib_entrada');

    popup_distribucion_salida = uicontrol(gcf, 'Style', 'PopupMenu', ...
       'String', 'Exponencial|Uniforme|Deterministica|Gamma|Beta|Lognormal|Normal|Weibull',...
       'Units', 'normalized',...
       'Value', distrib_salida , ...
       'Position', [0.78 0.75 0.12 0.1], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.2, ...
       'BackgroundColor', [.702 .702 .702], ...
       'HorizontalAlignment', 'Center', ...
       'Callback', 'popup_distrib_salida');
else
     popup_distribucion_entrada = uicontrol(gcf, 'Style', 'PopupMenu', ...
       'String', 'Exponencial|Uniforme|Deterministica|Gamma|Beta|Lognormal|Normal|Weibull|No Entrada',...
        'Units', 'normalized',...
        'Value', distribuciones_entrada(pasos) , ...
        'Position', [0.55 0.75 0.12 0.1], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.2, ...
       'BackgroundColor', [.702 .702 .702], ...
       'HorizontalAlignment', 'Center', ...
       'Callback', 'popup_distrib_entrada');

    popup_distribucion_salida = uicontrol(gcf, 'Style', 'PopupMenu', ...
       'String', 'Exponencial|Uniforme|Deterministica|Gamma|Beta|Lognormal|Normal|Weibull',...
       'Units', 'normalized',...
       'Value', distribuciones_salida(pasos) , ...
       'Position', [0.78 0.75 0.12 0.1], ...
        'FontUnits', 'normalized', ...
       	'FontSize', 0.2, ...
       'BackgroundColor', [.702 .702 .702], ...
       'HorizontalAlignment', 'Center', ...
       'Callback', 'popup_distrib_salida');
   
   distrib_entrada=distribuciones_entrada(pasos);
   distrib_salida=distribuciones_salida(pasos);
end





   
%Leemos el valor de la probabilidad de ir de un determinado de la red a otro
for j=1:nodos_abiertas
   texto_probabilidad=strcat('Probabilidad de ir al nodo nº ',num2str(j));
   
   text_redes_abiertas_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
   	'String', texto_probabilidad, ...
   	'Units', 'normalized', ...
	'Position', [0.3 (0.75-0.55*(j/(nodos_abiertas+1))) 0.35 0.05], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.4, ...
	'BackgroundColor', [.6 .6 .6],...
    'HorizontalAlignment', 'Center');  

  
   if (cambiar_parametros_mm==0) 
       prob_abiertas(j) = uicontrol(gcf, 'Style', 'Edit', ...
   	        'Units', 'normalized', ...
		    'Position', [0.7 (0.75-0.55*(j/(nodos_abiertas+1))) 0.08 0.05], ...
            'FontUnits', 'normalized', ...
            'FontSize', 0.4, ...
    	    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    else
        prob_abiertas(j) = uicontrol(gcf, 'Style', 'Edit', ...
            'String', num2str(matriz_prob_abiertas(j+1,pasos)), ...
   	        'Units', 'normalized', ...
		    'Position', [0.7 (0.75-0.55*(j/(nodos_abiertas+1))) 0.08 0.05], ...
            'FontUnits', 'normalized', ...
            'FontSize', 0.4, ...
    	    'BackgroundColor', [.702 .702 .702],...
            'HorizontalAlignment', 'Center');
    end

end      

clear texto1;
clear texto_redes_abiertas_probabilidad;


%Si se hace click en el boton de siguiente, se ejecuta el fichero 
%redes_abiertas_comprobar que se encarga de comprobar si los parametros
%introducidos son correctos. A su vez, el fichero redes_abiertas_comprobar
%volvera a llamar al fichero redes_abiertas mientras no se hayan leido
%los parametros de todos los nodos de la red

boton_redes_abiertas_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Siguiente >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.38 0.05 0.2 0.1], ...
  'FontUnits', 'normalized', ...
   'FontWeight', 'bold', ...
  'FontSize', 0.2, ...
  'Callback', 'redes_abiertas_simulacion_param');

end
