% PROYECTO FIN DE CARRERA - Jorge L. Vega Valle
% Fichero  redes_cerradas_salida.m

%Este fichero se encarga de mostrar los parametros de salida
%de la red:
%1.-El valor de L y W del ultimo nodo de la red.
%2.-El valor de la probabilidad media de clientes en el ultimo
%nodo de la red.
%3.-La probabilidad de que haya un determinado numero de usuarios
%en la red


%Cerramos la ventana anterior y creamos una nueva.

close(1)

cambiar_parametros_redes_cerradas=1;

figure('Units', 'normalized',...
	    'Position', [0.05 0.05 0.9 0.9],...
        'MenuBar', 'none', ...
        'name', 'Resolucion analitica: Resultados de la red de Jackson cerrada', ...
        'NumberTitle', 'off', ...
        'resize','off');
     
frame_redes_cerradas_salida_1 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.64 0.82 0.35]);     
     
frame_redes_cerradas_salida_2 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.33 0.82 0.07]);

frame_redes_cerradas_salida_3 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.16 0.82 0.17]);

frame_redes_cerradas_salida_4 = uicontrol(gcf, 'Style', 'Frame', ...
   'Units', 'normalized', ...
   'BackgroundColor', [.6 .6 .6],...
   'Position', [0.1 0.41 0.3 0.22]);

texto_clientes='Numero clientes=';

texto_clientes=strcat(texto_clientes, ' ',num2str(clientes_cerradas-1));

text_redes_cerradas_salida_0 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', texto_clientes, ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 0.93 0.20 0.05], ...
    	'BackgroundColor', [.6 .6 .6],...
	    'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');

text_redes_cerradas_salida_1 = uicontrol(gcf, 'Style', 'Text', ...
 	    'String', 'Resultados de cada nodo', ...
   	    'Units', 'normalized', ...
	    'Position', [0.35 0.93 0.4 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');
   
%Mostramos el valor de L y W para cada nodo de la red
   
for i=1:nodos_cerradas
   
   texto='Nodo';
   texto=strcat(texto,' ',' (',num2str(i),')');
   
   text_redes_cerradas_salida_nodo = uicontrol(gcf, 'Style', 'Text', ...
        'String', texto, ...
   	    'Units', 'normalized', ...
	    'Position', [0.12 0.95-0.3*i/nodos_cerradas 0.08 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold', ...
	    'FontSize', 0.4, ...
        'HorizontalAlignment', 'Center');   
   
   texto='Mu =';
   texto=strcat(texto, num2str(vector_mu_cerradas(i)),' y Servidores =',num2str(vector_servidores_cerradas(i)));
   
   text_redes_cerradas_informacion_nodo = uicontrol(gcf, 'Style', 'Text', ...
        'String', texto, ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 (0.95-0.3*i/nodos_cerradas) 0.25 0.02], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'ForegroundColor', 'b', ...     
       'HorizontalAlignment', 'Center');   
   
	text_redes_cerradas_salida_l = uicontrol(gcf, 'Style', 'Text', ...
          'String', 'L = ', ...
   	      'Units', 'normalized', ...
	      'Position', [0.30 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
          'BackgroundColor', [.6 .6 .6],...
          'FontUnits', 'normalized',...
    	  'FontSize', 0.3, ...
          'HorizontalAlignment', 'Center');   
   
	text_redes_cerradas_salida_l_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', num2str(vector_l_cerradas(i)), ...
       	'Units', 'normalized', ...
	    'Position', [0.37 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');   
    
  	text_redes_cerradas_salida_lq = uicontrol(gcf, 'Style', 'Text', ...
          'String', 'Lq = ', ...
   	      'Units', 'normalized', ...
	      'Position', [0.45 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
          'BackgroundColor', [.6 .6 .6],...
          'FontUnits', 'normalized',...
    	  'FontSize', 0.3, ...
          'HorizontalAlignment', 'Center');   
      
    auxiliar=(vector_l_cerradas(i)/vector_w_cerradas(i))*(vector_w_cerradas(i)-1/vector_mu_cerradas(i));
    
    if auxiliar<0.000001
        auxiliar=0;
    end
    
    %Lq=(L/W)*Wq   (Formula de Little)  
	text_redes_cerradas_salida_lq_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', num2str(auxiliar), ...
       	'Units', 'normalized', ...
	    'Position', [0.52 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');            
   
	text_redes_cerradas_salida_w = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'W = ', ...
       	'Units', 'normalized', ...
	    'Position', [0.60 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
        'HorizontalAlignment', 'Center');   
   
   
   
	text_redes_cerradas_salida_w_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', num2str(vector_w_cerradas(i)), ...
   	    'Units', 'normalized', ...
	    'Position', [0.67 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');   
    
    text_redes_cerradas_salida_wq = uicontrol(gcf, 'Style', 'Text', ...
          'String', 'Wq = ', ...
   	      'Units', 'normalized', ...
	      'Position', [0.75 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
          'BackgroundColor', [.6 .6 .6],...
          'FontUnits', 'normalized',...
    	  'FontSize', 0.3, ...
          'HorizontalAlignment', 'Center');   
      
      
    auxiliar=vector_w_cerradas(i)-1/vector_mu_cerradas(i);
    
    if (auxiliar<0.000001)
        auxiliar=0;
    end
      
    %Wq=W-1/mu (Formula de Little)  
	text_redes_cerradas_salida_wq_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', num2str(auxiliar), ...
   	    'Units', 'normalized', ...
	    'Position', [0.82 0.95-0.3*i/nodos_cerradas 0.06 0.05], ...
   	    'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.3, ...
   	    'HorizontalAlignment', 'Center');         
    
   
   
end

%Mostramos el valor de la probabilidad media de un determinado numero
%de clientes en el ultimo nodo de la red.

%for i=0:(clientes_cerradas-1)
         
%   texto_cerradas=strcat('Prob. nº clientes en ultimo nodo = ',' ',num2str(i));

      
%	text_redes_cerradas_salida_p_1 = uicontrol(gcf, 'Style', 'Text', ...
%      'String', texto_cerradas, ...
%   	'Units', 'normalized', ...
%	   'Position', [0.15 0.8-0.48*(i+1)/(clientes_cerradas+1) 0.40 0.05], ...
%   	'BackgroundColor', [.6 .6 .6],...
%	   'FontSize', 12, ...
%      'HorizontalAlignment', 'Center');  
      
%   aux=num2str(nummedio(i+1));
   
%  	text_redes_cerradas_salida_p_2 = uicontrol(gcf, 'Style', 'Text', ...
%      'String', aux, ...
%   	'Units', 'normalized', ...
%	   'Position', [0.60 0.8-0.48*(i+1)/(clientes_cerradas+1) 0.10 0.05], ...
%   	'BackgroundColor', [.6 .6 .6],...
%	   'FontSize', 12, ...
%   	'HorizontalAlignment', 'Center');   
   
   
   
%	end
   
   
   
   
text_probabilidad_dibujar = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'Dibujar entre ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 0.55 0.09 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
   
text_probabilidad_dibujar_2 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'p', ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 0.50 0.03 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');     
   
numero_clientes_intervalo1 = uicontrol(gcf, 'Style', 'Edit', ...
   	    'Units', 'normalized', ...
	    'Position', [0.15 0.50 0.08 0.03], ...
        'BackgroundColor', [.702 .702 .702],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
text_probabilidad_dibujar_3 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'y p', ...
   	    'Units', 'normalized', ...
	    'Position', [0.24 0.50 0.03 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');     
   
numero_clientes_intervalo2 = uicontrol(gcf, 'Style', 'Edit', ...
       	'Units', 'normalized', ...
	    'Position', [0.28 0.50 0.08 0.03], ...
        'BackgroundColor', [.702 .702 .702],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');     
   
   
text_probabilidad_dibujar_4 = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'en el nodo ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 0.45 0.09 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');     
   
numero_nodo_intervalo_dibujar = uicontrol(gcf, 'Style', 'Edit', ...
   	    'Units', 'normalized', ...
	    'Position', [0.21 0.45 0.08 0.03], ...
        'BackgroundColor', [.702 .702 .702],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
   
text_probabilidad_nodo_ok = uicontrol(gcf, 'Style', 'Pushbutton', ...
        'String', 'Dibujar ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.3 0.45 0.05 0.03], ...
        'BackgroundColor', [.702 .702 .702],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center',...
        'Callback', 'dibujar_p_cerradas');           
   




text_probabilidad_nodo = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'Probabilidad ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.11 0.35 0.09 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
numero_clientes_probabilidad = uicontrol(gcf, 'Style', 'Edit', ...
   	   'Units', 'normalized', ...
	   'Position', [0.21 0.35 0.08 0.03], ...
       'BackgroundColor', [.702 .702 .702],...
       'FontUnits', 'normalized',...
	   'FontSize', 0.5, ...
       'HorizontalAlignment', 'Center');  
   
   
text_probabilidad_nodo = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'clientes en el nodo ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.3 0.35 0.2 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');     
   
numero_nodo_probabilidad = uicontrol(gcf, 'Style', 'Edit', ...
   	   'Units', 'normalized', ...
	   'Position', [0.51 0.35 0.08 0.03], ...
       'BackgroundColor', [.702 .702 .702],...
       'FontUnits', 'normalized',...
	   'FontSize', 0.5, ...
       'HorizontalAlignment', 'Center');  

   
text_probabilidad_nodo_ok = uicontrol(gcf, 'Style', 'Pushbutton', ...
        'String', 'OK ', ...
   	    'Units', 'normalized', ...
	    'Position', [0.6 0.35 0.05 0.03], ...
        'BackgroundColor', [.702 .702 .702],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center', ...
        'Callback', 'calcular_p_clientes_cerradas');        


   
%Mostramos el valor de la probabilida de que haya un determinado numero 
%de elementos en cada nodo de la red

text_probabilidad = uicontrol(gcf, 'Style', 'Text', ...
        'String', 'Probabilidad de un determinado numero de clientes en cada nodo:', ...
   	    'Units', 'normalized', ...
	    'Position', [0.2 0.29 0.7 0.03], ...
        'BackgroundColor', [.6 .6 .6],...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
        'HorizontalAlignment', 'Center');  
   
%Leemos el valor del numero de elementos en cada nodo de la red   
for i=1:nodos_cerradas
         
   texto_cerradas=num2str(i);

	text_redes_cerradas_salida_nodo = uicontrol(gcf, 'Style', 'Text', ...
       	'String', texto_cerradas, ...
   	    'Units', 'normalized', ...
		'Position', [0.10+0.72*i/(nodos_cerradas+1) 0.245   0.02 0.03], ...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
		'BackgroundColor', [.6 .6 .6],...
        'HorizontalAlignment', 'Center');
   
   elementos(i) = uicontrol(gcf, 'Style', 'Edit', ...
  		'Units', 'normalized', ...
		'Position', [0.13+0.72*i/(nodos_cerradas+1) 0.245   0.05 0.04], ...
        'FontUnits', 'normalized',...
	    'FontSize', 0.5, ...
		'BackgroundColor', [.702 .702 .702],...
        'HorizontalAlignment', 'Center');

end

%Si se hace click en el boton calcular se ejecuta calcular_p_cerradas que 
%calcula la probabilidad de que haya exactamente un determinado numero
%de clientes en cada nodo de la red

boton_redes_cerradas_salida_calcular = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Calcular', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.43 0.18 0.1 0.04], ...
  'FontUnits', 'normalized',...
  'FontSize', 0.5, ...
  'Callback', 'calcular_p_cerradas'); 

%Si se hace click en siguiente, se ejecuta el contenido del fichero llamado
%aquas

boton_redes_cerradas_salida_sig = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Menu Inicio >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.2 0.05 0.2 0.07], ...
  'FontUnits', 'normalized',...
  'FontSize', 0.3, ...
  'Callback', 'aquas');


boton_redes_cerradas_salida_cambiar_parametros = uicontrol(gcf, 'Style', 'Pushbutton',...
  'String', 'Cambiar los parametros del problema >>', 'Value', 0, ...
  'Units', 'normalized', ...
  'Position', [0.5 0.05 0.3 0.07], ...
  'FontUnits', 'normalized',...
  'FontSize', 0.3, ...
  'Callback', 'cambiar_parametros_cerradas');
